# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt
# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

# Copy the rest of the application code into the container
COPY . /app

# Define environment variables (if needed)
ENV DEPLOYMENT_ENV=development

# Expose any necessary ports
# EXPOSE 8080


# Define the command to run your application
CMD ["python", "app.py"]